module HomepageHelper
  def radio_button_render
    str = ""
    [ 'Yes Please!', 'NO', 'Pick-Up Only (city)', 'Delivery Only (city)'].each do |theme|
      str << "<br>"
      str << (radio_button_tag 'theme', theme, theme).to_s
      str << '&nbsp;&nbsp;' + (theme.humanize).to_s
    end
    str.html_safe
  end

  def valid_to_send?(elms)
    #trust the user and UI that required if filled out
    is_valid = true
    %W[ name phone email furniture services ].each do |val|
      if elms[val].blank?
        is_valid = false
        break
      end
    end
    return is_valid
  end

  def safe_service
    link_to 'SERVICES', service_path
  end

  def home_service
    link_to 'HOME', root_path
  end

  def restrap_box
    str = ""
    str+= %Q| <span class="s_box_header">STRAPS/VINYL </span> |
    str+= %Q| </br>        |
    str+= %Q| </br>        |
    str+= %Q| Replace the existing vinyl on furniture by choosing from a wide variety of colors. |
    str+= %Q| </br> |
    str+= %Q| You can choose to do one color for all the straps or add your own style by adding |
    str+= %Q| </br> |
    str+= %Q| accept strap colors. |
    str+= %Q| </br> |
    str+= %Q| </br> |
    str+= %Q| Complete refinish includes sandblast & powdercoating the frame and re-strapping. |
    str.html_safe
  end

  def resling_box
    str = ""
    str+= %Q| <span class="s_box_header"> RE-SLING </span>    |
    str+= %Q| </br>        |
    str+= %Q| </br>        |
    str+= %Q| Place new sling fabric on your furniture. We will make a customized sling to fit |
    str+= %Q| </br> |
    str+= %Q| perfectly your existing piece of furniture. Our most popular replaces are on chaise lounges, |
    str+= %Q| dining chairs, barstools and swivel/rockers. We use the best quality </br> fabric in the market, |
    str+= %Q| which lasts an average of 5 years. |
    str+= %Q| </br> |
    str+= %Q| </br> |
    str+= %Q| We also offer padded slings for greater comfort. |
    str+= %Q| </br> |
    str+= %Q| Complete refinish includes sandblast & powdercoating the frame and re-sling. |
    str.html_safe
  end

  def sandblast_box
    str = ""
    str+= %Q| <span class="s_box_header"> Sandblast & Powdercoat </span>    |
    str+= %Q| </br>        |
    str+= %Q| </br>        |
    str+= %Q| Our sand blast process involves removing all paint from the furniture down to the bare metal, |
    str+= %Q| which allows for improved texture. An electrostatic powdercoating is then used,  |
    str+= %Q| in which a paint powder is applied to the frame and cured in an oven at high temperatures, |
    str+= %Q| giving the furniture a thick and durable painted finish. |
    str+= %Q| </br> |
    str+= %Q| Powdercoating finishes are three times as thick as paint. |
    str+= %Q| </br> |
    str+= %Q| </br> |
    str+= %Q| We also offer an optional metalizing process for steel, cast iron, aluminum and wrought iron furniture.  |
    str+= %Q| If applicable, the furniture is then completed with vinyl strapping, slings and/or cushions, and glides.  |
    str+= %Q| </br> |
    str+= %Q| </br> |
    str+= %Q| We can strip & powdercoat almost any item made of metal: Tables, chairs, umbrella bases, chaise lounges, baker’s racks and even gate panels. |
    str.html_safe
  end

  def cushion_box
    str = ""
    str+= %Q| <span class="s_box_header"> Cushions </span>    |
    str+= %Q| </br>        |
    str+= %Q| </br>        |
    str+= %Q| Cushions are custom made to fit your furniture perfectly. You can choose to add piping, |
    str+= %Q| striped fabric and ties to enhance style. Cushions will transform your patio furniture |
    str+= %Q| experience by bringing you comfort and edge. |
    str+= %Q| </br>        |
    str+= %Q| </br>        |
    str+= %Q| Please note that lead time is 4 to 5 weeks for special order fabrics.  |
    str.html_safe
  end

  def umbrella_box
    str = ""
    str+= %Q| <span class="s_box_header"> Umbrella </span>    |
    str+= %Q| </br>        |
    str+= %Q| </br>        |
    str+= %Q| Our most popular umbrella repairs consist of replacing parts, creating customized umbrella  |
    str+= %Q| covers with Sunbrella fabrics and strip & powder coating umbrella bases.  |
    str.html_safe
  end

  def table_box
    str = ""
    str+= %Q| <span class="s_box_header"> Table  </span>      |
    str+= %Q| </br>        |
    str+= %Q| </br>        |
    str+= %Q| Refinish your table by replacing the table top (stone, tempered glass, acrylic or solid) and strip & powdercoating.  |
    str.html_safe
  end

  def resling_fabric_pic
    {
      "Forest Hills" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/1131_Forest Hills",
                          :big => "Services/Re-Sling/Fabric_Selection/1131_Forest Hills" },
      "Bogota" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/1174_Bogota",
                    :big => "Services/Re-Sling/Fabric_Selection/1174_Bogota" },
      "Caracas" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/1176_Caracas",
                     :big => "Services/Re-Sling/Fabric_Selection/1176_Caracas" },
      "Deerfield" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/5900_Deerfield",
                       :big => "Services/Re-Sling/Fabric_Selection/5900_Deerfield" },
      "Natural Raffia" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/5903_Natural Raffia",
                            :big => "Services/Re-Sling/Fabric_Selection/5903_Natural Raffia" },
      "Golden Lanthern" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/10230_Golden Lantern",
                             :big => "Services/Re-Sling/Fabric_Selection/10230_Golden Lantern"},
      "Rincon" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/10321_Rincon",
                    :big => "Services/Re-Sling/Fabric_Selection/10321_Rincon" },
      "Crystal Cove" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/11236_Crystal Cove",
                          :big => "Services/Re-Sling/Fabric_Selection/11236_Crystal Cove" },
      "Metallica" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/11309_Metallica",
                       :big => "Services/Re-Sling/Fabric_Selection/11309_Metallica" },
      "East Wood" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/11313_East Wood",
                       :big => "Services/Re-Sling/Fabric_Selection/11313_East Wood" },
      "Taylor" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/12176_Taylor",
                    :big => "Services/Re-Sling/Fabric_Selection/12176_Taylor" },
      "Blue Lantern" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/12229_blue_lantern",
                          :big => "Services/Re-Sling/Fabric_Selection/12229_blue_lantern" },
      "Suri" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/12235_Suri",
                  :big => "Services/Re-Sling/Fabric_Selection/12235_Suri" },
      "Watercolor Tweed" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/12327_Watercolor_Tweed",
                              :big => "Services/Re-Sling/Fabric_Selection/12327_Watercolor_Tweed" },
      "Lacroix" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/12336_lacroix",
                     :big => "Services/Re-Sling/Fabric_Selection/12336_lacroix" },
      "Mia II" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/12360_Mia_II",
                    :big => "Services/Re-Sling/Fabric_Selection/12360_Mia_II" },
      "Palm Springs" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/13163_Palm_Springs",
                          :big => "Services/Re-Sling/Fabric_Selection/13163_Palm_Springs" },
      "Cherrywood" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/13233_Cherrywood",
                        :big => "Services/Re-Sling/Fabric_Selection/13233_Cherrywood" },
      "Sparkling Water" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/13381_Sparkling_Water",
                              :big => "Services/Re-Sling/Fabric_Selection/13381_Sparkling_Water" },
      "Nocciola" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/14130_Nocciola",
                      :big => "Services/Re-Sling/Fabric_Selection/14130_Nocciola" },
      "Luxor" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/15222_Luxor",
                   :big => "Services/Re-Sling/Fabric_Selection/15222_Luxor" },
      "Sutter" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/18303_Sutter",
                    :big => "Services/Re-Sling/Fabric_Selection/18303_Sutter" },
      "Champagne" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/19209_Champagne",
                       :big => "Services/Re-Sling/Fabric_Selection/19209_Champagne" },
      "Lemon Lime" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/20273_Lemon_Lime",
                        :big => "Services/Re-Sling/Fabric_Selection/20273_Lemon_Lime" },
      "Mariner" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/20325_Mariner",
                     :big => "Services/Re-Sling/Fabric_Selection/20325_Mariner" },
      "Augusta" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/22109_Augusta",
                     :big => "Services/Re-Sling/Fabric_Selection/22109_Augusta" },
      "Cobble Stone" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/29321_Cobble Stone",
                          :big => "Services/Re-Sling/Fabric_Selection/29321_Cobble Stone" },
      "Pepperwood" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/29323_Pepperwood",
                        :big => "Services/Re-Sling/Fabric_Selection/29323_Pepperwood" },
      "Lapis" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/39106_Lapis",
                   :big => "Services/Re-Sling/Fabric_Selection/39106_Lapis" },
      "Caballeros" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/40330_Caballeros",
                        :big => "Services/Re-Sling/Fabric_Selection/40330_Caballeros" },
      "Chimayo" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/40335_Chimayo",
                     :big => "Services/Re-Sling/Fabric_Selection/40335_Chimayo" },
      "Seagull" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/41118_Seagull",
                     :big => "Services/Re-Sling/Fabric_Selection/41118_Seagull" },
      "River Bed" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/43322_River_Bed",
                       :big => "Services/Re-Sling/Fabric_Selection/43322_River_Bed" },
      "Turquesa" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/45334_Turquesa",
                      :big => "Services/Re-Sling/Fabric_Selection/45334_Turquesa" },
      "Coco Weave" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/46209_Coco_Weave",
                        :big => "Services/Re-Sling/Fabric_Selection/46209_Coco_Weave"} ,
      "Ecuador" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/52127_Ecuador",
                     :big => "Services/Re-Sling/Fabric_Selection/52127_Ecuador" },
      "Cardamon" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/54156_Cardamon",
                      :big => "Services/Re-Sling/Fabric_Selection/54156_Cardamon" },
      "Melbourne" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/54162_Melbourne",
                       :big => "Services/Re-Sling/Fabric_Selection/54162_Melbourne" },
      "Havana" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/54164_Havana",
                    :big => "Services/Re-Sling/Fabric_Selection/54164_Havana" },
      "Crossings-Earth" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/71153_Crossings-Earth",
                             :big => "Services/Re-Sling/Fabric_Selection/71153_Crossings-Earth" },
      "Dupione Walnut" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/8017_Dupione_Walnut",
                            :big => "Services/Re-Sling/Fabric_Selection/8017_Dupione_Walnut" },
      "Gold Coast" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/11370_Gold_Coast",
                        :big => "Services/Re-Sling/Fabric_Selection/11370_Gold_Coast" },
      "Tarragon" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/12174_Tarragon",
                      :big => "Services/Re-Sling/Fabric_Selection/12174_Tarragon" },
      "Royal Blue" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/14346_Royal_Blue",
                        :big => "Services/Re-Sling/Fabric_Selection/14346_Royal_Blue" },
      "Cape Cove" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/19210_Cape_Cove",
                       :big => "Services/Re-Sling/Fabric_Selection/19210_Cape_Cove" },
      "Hennessey" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/20116_Hennessey",
                       :big => "Services/Re-Sling/Fabric_Selection/20116_Hennessey" },
      "Valencia" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/20301_Valencia",
                      :big => "Services/Re-Sling/Fabric_Selection/20301_Valencia" },
      "Weston" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/21303_Weston",
                    :big => "Services/Re-Sling/Fabric_Selection/21303_Weston" },
      "Phantom" => { :small => "Services/Re-Sling/Circle_Fabric_Selection/11305_Phantom",
                     :big => "Services/Re-Sling/Fabric_Selection/11305_Phantom"}
    }
  end

  def resling_finish_pic
    {
      "Snow" => { :small => "Services/Re-Sling/Circle_Finish_Selection/SNO_Snow",
                  :big => "Services/Re-Sling/Finish_Selection/SNO_Snow" },
      "Parchment" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PMT_Parchment",
                       :big => "Services/Re-Sling/Finish_Selection/PMT_Parchment" },
      "Shell" => { :small => "Services/Re-Sling/Circle_Finish_Selection/SHL_Shell",
                   :big => "Services/Re-Sling/Finish_Selection/SHL_Shell" },
      "Sonora"=> { :small => "Services/Re-Sling/Circle_Finish_Selection/SNR_Sonora",
                   :big => "Services/Re-Sling/Finish_Selection/SNR_Sonora" },
      "Moab" => { :small => "Services/Re-Sling/Circle_Finish_Selection/MOA_Moab",
                  :big => "Services/Re-Sling/Finish_Selection/MOA_Moab" },
      "Almond Silk" => { :small => "Services/Re-Sling/Circle_Finish_Selection/ASK_Almond_Silk",
                         :big => "Services/Re-Sling/Finish_Selection/ASK_Almond_Silk" },
      "Greco" => { :small => "Services/Re-Sling/Circle_Finish_Selection/GRE_Greco",
                   :big => "Services/Re-Sling/Finish_Selection/GRE_Greco" },
      "Bronze Mica" => { :small => "Services/Re-Sling/Circle_Finish_Selection/BZM_Bronze_Mica",
                         :big => "Services/Re-Sling/Finish_Selection/BZM_Bronze_Mica" },
      "Aged Bronze" => { :small => "Services/Re-Sling/Circle_Finish_Selection/ABR_Aged_Bronze",
                         :big => "Services/Re-Sling/Finish_Selection/ABR_Aged_Bronze" },
      "Rich Earth" => { :small => "Services/Re-Sling/Circle_Finish_Selection/REA_Rich_Earth",
                        :big => "Services/Re-Sling/Finish_Selection/REA_Rich_Earth" },
      "Graphite" => { :small => "Services/Re-Sling/Circle_Finish_Selection/GPH_Graphite",
                      :big => "Services/Re-Sling/Finish_Selection/GPH_Graphite" },
      "Mocha" => { :small => "Services/Re-Sling/Circle_Finish_Selection/MOC_Mocha",
                   :big => "Services/Re-Sling/Finish_Selection/MOC_Mocha" },
      "Titanium" => { :small => "Services/Re-Sling/Circle_Finish_Selection/TIN_Titanium",
                      :big => "Services/Re-Sling/Finish_Selection/TIN_Titanium" },
      "Aluminum Metal" => { :small => "Services/Re-Sling/Circle_Finish_Selection/ALM_Aluminum_Metal",
                            :big => "Services/Re-Sling/Finish_Selection/ALM_Aluminum_Metal" },
      "Woodland Green" => { :small => "Services/Re-Sling/Circle_Finish_Selection/WLD_Woodland Green",
                            :big => "Services/Re-Sling/Finish_Selection/WLD_Woodland Green" },
      "Cobalt" => { :small => "Services/Re-Sling/Circle_Finish_Selection/CBL_Cobalt",
                    :big => "Services/Re-Sling/Finish_Selection/CBL_Cobalt" },
      "Merlot" => { :small => "Services/Re-Sling/Circle_Finish_Selection/MER_Merlot",
                    :big => "Services/Re-Sling/Finish_Selection/MER_Merlot" },
      "Obsidian" => { :small => "Services/Re-Sling/Circle_Finish_Selection/OBS_Obsidian",
                      :big => "Services/Re-Sling/Finish_Selection/OBS_Obsidian" },
      "Forest Green" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-251_Forest_Green",
                          :big => "Services/Re-Sling/Finish_Selection/PC-251_Forest_Green" },
      "Burgundy" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-236_Burgundy",
                      :big => "Services/Re-Sling/Finish_Selection/PC-236_Burgundy" },
      "French Blue" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-215_French_Blue",
                         :big => "Services/Re-Sling/Finish_Selection/PC-215_French_Blue" },
      "Grey" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-219_Grey",
                  :big => "Services/Re-Sling/Finish_Selection/PC-219_Grey" },
      "Navy Blue" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-217_Navy_Blue",
                       :big => "Services/Re-Sling/Finish_Selection/PC-217_Navy_Blue" },
      "Dark Green" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-212_Dark_Green",
                        :big => "Services/Re-Sling/Finish_Selection/PC-212_Dark_Green" },
      "Camel" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-206_Camel",
                   :big => "Services/Re-Sling/Finish_Selection/PC-206_Camel" },
      "Coffee" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-238_Coffee",
                    :big => "Services/Re-Sling/Finish_Selection/PC-238_Coffee" },
      "Leisure Brown"=> { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-231_Leisure_Brown",
                          :big => "Services/Re-Sling/Finish_Selection/PC-231_Leisure_Brown" },
      "Adobe" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-232_Adobe",
                   :big => "Services/Re-Sling/Finish_Selection/PC-232_Adobe" },
      "Dove" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-252_Dove",
                  :big => "Services/Re-Sling/Finish_Selection/PC-252_Dove" },
      "Citron Yellow" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-204_Citron_Yellow",
                           :big => "Services/Re-Sling/Finish_Selection/PC-204_Citron_Yellow" }
    }
  end

  def restrap_finish_pic
    {
      "Snow" => { :small => "Services/Re-Sling/Circle_Finish_Selection/SNO_Snow",
                  :big => "Services/Re-Sling/Finish_Selection/SNO_Snow" },
      "Parchment" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PMT_Parchment",
                       :big => "Services/Re-Sling/Finish_Selection/PMT_Parchment" },
      "Shell" => { :small => "Services/Re-Sling/Circle_Finish_Selection/SHL_Shell",
                   :big => "Services/Re-Sling/Finish_Selection/SHL_Shell" },
      "Sonora"=> { :small => "Services/Re-Sling/Circle_Finish_Selection/SNR_Sonora",
                   :big => "Services/Re-Sling/Finish_Selection/SNR_Sonora" },
      "Moab" => { :small => "Services/Re-Sling/Circle_Finish_Selection/MOA_Moab",
                  :big => "Services/Re-Sling/Finish_Selection/MOA_Moab" },
      "Almond Silk" => { :small => "Services/Re-Sling/Circle_Finish_Selection/ASK_Almond_Silk",
                         :big => "Services/Re-Sling/Finish_Selection/ASK_Almond_Silk" },
      "Greco" => { :small => "Services/Re-Sling/Circle_Finish_Selection/GRE_Greco",
                   :big => "Services/Re-Sling/Finish_Selection/GRE_Greco" },
      "Bronze Mica" => { :small => "Services/Re-Sling/Circle_Finish_Selection/BZM_Bronze_Mica",
                         :big => "Services/Re-Sling/Finish_Selection/BZM_Bronze_Mica" },
      "Aged Bronze" => { :small => "Services/Re-Sling/Circle_Finish_Selection/ABR_Aged_Bronze",
                         :big => "Services/Re-Sling/Finish_Selection/ABR_Aged_Bronze" },
      "Rich Earth" => { :small => "Services/Re-Sling/Circle_Finish_Selection/REA_Rich_Earth",
                        :big => "Services/Re-Sling/Finish_Selection/REA_Rich_Earth" },
      "Graphite" => { :small => "Services/Re-Sling/Circle_Finish_Selection/GPH_Graphite",
                      :big => "Services/Re-Sling/Finish_Selection/GPH_Graphite" },
      "Mocha" => { :small => "Services/Re-Sling/Circle_Finish_Selection/MOC_Mocha",
                   :big => "Services/Re-Sling/Finish_Selection/MOC_Mocha" },
      "Titanium" => { :small => "Services/Re-Sling/Circle_Finish_Selection/TIN_Titanium",
                      :big => "Services/Re-Sling/Finish_Selection/TIN_Titanium" },
      "Aluminum Metal" => { :small => "Services/Re-Sling/Circle_Finish_Selection/ALM_Aluminum_Metal",
                            :big => "Services/Re-Sling/Finish_Selection/ALM_Aluminum_Metal" },
      "Woodland Green" => { :small => "Services/Re-Sling/Circle_Finish_Selection/WLD_Woodland Green",
                            :big => "Services/Re-Sling/Finish_Selection/WLD_Woodland Green" },
      "Cobalt" => { :small => "Services/Re-Sling/Circle_Finish_Selection/CBL_Cobalt",
                    :big => "Services/Re-Sling/Finish_Selection/CBL_Cobalt" },
      "Merlot" => { :small => "Services/Re-Sling/Circle_Finish_Selection/MER_Merlot",
                    :big => "Services/Re-Sling/Finish_Selection/MER_Merlot" },
      "Obsidian" => { :small => "Services/Re-Sling/Circle_Finish_Selection/OBS_Obsidian",
                      :big => "Services/Re-Sling/Finish_Selection/OBS_Obsidian" },
      "Forest Green" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-251_Forest_Green",
                          :big => "Services/Re-Sling/Finish_Selection/PC-251_Forest_Green" },
      "Burgundy" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-236_Burgundy",
                      :big => "Services/Re-Sling/Finish_Selection/PC-236_Burgundy" },
      "French Blue" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-215_French_Blue",
                         :big => "Services/Re-Sling/Finish_Selection/PC-215_French_Blue" },
      "Grey" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-219_Grey",
                  :big => "Services/Re-Sling/Finish_Selection/PC-219_Grey" },
      "Navy Blue" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-217_Navy_Blue",
                       :big => "Services/Re-Sling/Finish_Selection/PC-217_Navy_Blue" },
      "Dark Green" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-212_Dark_Green",
                        :big => "Services/Re-Sling/Finish_Selection/PC-212_Dark_Green" },
      "Camel" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-206_Camel",
                   :big => "Services/Re-Sling/Finish_Selection/PC-206_Camel" },
      "Coffee" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-238_Coffee",
                    :big => "Services/Re-Sling/Finish_Selection/PC-238_Coffee" },
      "Leisure Brown"=> { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-231_Leisure_Brown",
                          :big => "Services/Re-Sling/Finish_Selection/PC-231_Leisure_Brown" },
      "Adobe" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-232_Adobe",
                   :big => "Services/Re-Sling/Finish_Selection/PC-232_Adobe" },
      "Dove" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-252_Dove",
                  :big => "Services/Re-Sling/Finish_Selection/PC-252_Dove" },
      "Citron Yellow" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-204_Citron_Yellow",
                           :big => "Services/Re-Sling/Finish_Selection/PC-204_Citron_Yellow" }
    }
  end

  def restrap_vinyl_pic
    {
      "Aged Bronze" => { :small => "Services/Re-Strap/Circle_Vinyl_Colors/aged_bronze",
                         :big => "Services/Re-Strap/Vinyl_Colors/aged_bronze" },
      "Almond Silk" => { :small => "Services/Re-Strap/Circle_Vinyl_Colors/almond_silk",
                         :big => "Services/Re-Strap/Vinyl_Colors/almond_silk" },
      "Aluminum Metallicalm" => { :small => "Services/Re-Strap/Circle_Vinyl_Colors/aluminum_metallic_alm",
                                  :big => "Services/Re-Strap/Vinyl_Colors/aluminum_metallic_alm" },
      "Bronze Mica" => { :small => "Services/Re-Strap/Circle_Vinyl_Colors/bronze_mica",
                         :big => "Services/Re-Strap/Vinyl_Colors/bronze_mica" },
      "Cobalt" => { :small => "Services/Re-Strap/Circle_Vinyl_Colors/cobalt",
                    :big => "Services/Re-Strap/Vinyl_Colors/cobalt" },
      "Expresso" => { :small => "Services/Re-Strap/Circle_Vinyl_Colors/espresso",
                      :big => "Services/Re-Strap/Vinyl_Colors/espresso" },
      "Graphite" => { :small => "Services/Re-Strap/Circle_Vinyl_Colors/graphite",
                      :big => "Services/Re-Strap/Vinyl_Colors/graphite" },
      "Greco" => { :small => "Services/Re-Strap/Circle_Vinyl_Colors/greco",
                   :big => "Services/Re-Strap/Vinyl_Colors/greco" },
      "Merlot" => { :small => "Services/Re-Strap/Circle_Vinyl_Colors/merlot",
                    :big => "Services/Re-Strap/Vinyl_Colors/merlot" },
      "Moab" => { :small => "Services/Re-Strap/Circle_Vinyl_Colors/moab",
                  :big => "Services/Re-Strap/Vinyl_Colors/moab" },
      "Mocha" => { :small => "Services/Re-Strap/Circle_Vinyl_Colors/mocha",
                   :big => "Services/Re-Strap/Vinyl_Colors/mocha" },
      "Obsidian" => { :small => "Services/Re-Strap/Circle_Vinyl_Colors/obsidian",
                      :big => "Services/Re-Strap/Vinyl_Colors/obsidian" },
      "Parchment" => { :small => "Services/Re-Strap/Circle_Vinyl_Colors/parchment",
                       :big => "Services/Re-Strap/Vinyl_Colors/parchment" },
      "Shell" => { :small => "Services/Re-Strap/Circle_Vinyl_Colors/shell",
                   :big => "Services/Re-Strap/Vinyl_Colors/shell" },
      "Snow" => { :small => "Services/Re-Strap/Circle_Vinyl_Colors/snow",
                  :big => "Services/Re-Strap/Vinyl_Colors/snow" },
      "Sonora" => { :small => "Services/Re-Strap/Circle_Vinyl_Colors/sonora",
                    :big => "Services/Re-Strap/Vinyl_Colors/sonora" },
      "Titanium" => { :small => "Services/Re-Strap/Circle_Vinyl_Colors/titanium",
                      :big => "Services/Re-Strap/Vinyl_Colors/titanium" },
      "Woodland" => { :small => "Services/Re-Strap/Circle_Vinyl_Colors/woodland",
                      :big => "Services/Re-Strap/Vinyl_Colors/woodland" },
      "Forest Green" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-251_Forest_Green",
                          :big => "Services/Re-Sling/Finish_Selection/PC-251_Forest_Green" },
      "Burgundy" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-236_Burgundy",
                      :big => "Services/Re-Sling/Finish_Selection/PC-236_Burgundy" },
      "French Blue" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-215_French_Blue",
                         :big => "Services/Re-Sling/Finish_Selection/PC-215_French_Blue" },
      "Grey" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-219_Grey",
                  :big => "Services/Re-Sling/Finish_Selection/PC-219_Grey" },
      "Navy Blue" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-217_Navy_Blue",
                       :big => "Services/Re-Sling/Finish_Selection/PC-217_Navy_Blue" },
      "Dark Green" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-212_Dark_Green",
                        :big => "Services/Re-Sling/Finish_Selection/PC-212_Dark_Green" },
      "Camel" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-206_Camel",
                   :big => "Services/Re-Sling/Finish_Selection/PC-206_Camel" },
      "Coffee" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-238_Coffee",
                    :big => "Services/Re-Sling/Finish_Selection/PC-238_Coffee" },
      "Leisure Brown"=> { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-231_Leisure_Brown",
                          :big => "Services/Re-Sling/Finish_Selection/PC-231_Leisure_Brown" },
      "Adobe" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-232_Adobe",
                   :big => "Services/Re-Sling/Finish_Selection/PC-232_Adobe" },
      "Dove" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-252_Dove",
                  :big => "Services/Re-Sling/Finish_Selection/PC-252_Dove" },
      "Citron Yellow" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-204_Citron_Yellow",
                           :big => "Services/Re-Sling/Finish_Selection/PC-204_Citron_Yellow" }
    }
  end

  def powdercoat_finish_pic
    {
      "Snow" => { :small => "Services/Re-Sling/Circle_Finish_Selection/SNO_Snow",
                  :big => "Services/Re-Sling/Finish_Selection/SNO_Snow" },
      "Parchment" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PMT_Parchment",
                       :big => "Services/Re-Sling/Finish_Selection/PMT_Parchment" },
      "Shell" => { :small => "Services/Re-Sling/Circle_Finish_Selection/SHL_Shell",
                   :big => "Services/Re-Sling/Finish_Selection/SHL_Shell" },
      "Sonora"=> { :small => "Services/Re-Sling/Circle_Finish_Selection/SNR_Sonora",
                   :big => "Services/Re-Sling/Finish_Selection/SNR_Sonora" },
      "Moab" => { :small => "Services/Re-Sling/Circle_Finish_Selection/MOA_Moab",
                  :big => "Services/Re-Sling/Finish_Selection/MOA_Moab" },
      "Almond Silk" => { :small => "Services/Re-Sling/Circle_Finish_Selection/ASK_Almond_Silk",
                         :big => "Services/Re-Sling/Finish_Selection/ASK_Almond_Silk" },
      "Greco" => { :small => "Services/Re-Sling/Circle_Finish_Selection/GRE_Greco",
                   :big => "Services/Re-Sling/Finish_Selection/GRE_Greco" },
      "Bronze Mica" => { :small => "Services/Re-Sling/Circle_Finish_Selection/BZM_Bronze_Mica",
                         :big => "Services/Re-Sling/Finish_Selection/BZM_Bronze_Mica" },
      "Aged Bronze" => { :small => "Services/Re-Sling/Circle_Finish_Selection/ABR_Aged_Bronze",
                         :big => "Services/Re-Sling/Finish_Selection/ABR_Aged_Bronze" },
      "Rich Earth" => { :small => "Services/Re-Sling/Circle_Finish_Selection/REA_Rich_Earth",
                        :big => "Services/Re-Sling/Finish_Selection/REA_Rich_Earth" },
      "Graphite" => { :small => "Services/Re-Sling/Circle_Finish_Selection/GPH_Graphite",
                      :big => "Services/Re-Sling/Finish_Selection/GPH_Graphite" },
      "Mocha" => { :small => "Services/Re-Sling/Circle_Finish_Selection/MOC_Mocha",
                   :big => "Services/Re-Sling/Finish_Selection/MOC_Mocha" },
      "Titanium" => { :small => "Services/Re-Sling/Circle_Finish_Selection/TIN_Titanium",
                      :big => "Services/Re-Sling/Finish_Selection/TIN_Titanium" },
      "Aluminum Metal" => { :small => "Services/Re-Sling/Circle_Finish_Selection/ALM_Aluminum_Metal",
                            :big => "Services/Re-Sling/Finish_Selection/ALM_Aluminum_Metal" },
      "Woodland Green" => { :small => "Services/Re-Sling/Circle_Finish_Selection/WLD_Woodland Green",
                            :big => "Services/Re-Sling/Finish_Selection/WLD_Woodland Green" },
      "Cobalt" => { :small => "Services/Re-Sling/Circle_Finish_Selection/CBL_Cobalt",
                    :big => "Services/Re-Sling/Finish_Selection/CBL_Cobalt" },
      "Merlot" => { :small => "Services/Re-Sling/Circle_Finish_Selection/MER_Merlot",
                    :big => "Services/Re-Sling/Finish_Selection/MER_Merlot" },
      "Obsidian" => { :small => "Services/Re-Sling/Circle_Finish_Selection/OBS_Obsidian",
                      :big => "Services/Re-Sling/Finish_Selection/OBS_Obsidian" },
      "Forest Green" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-251_Forest_Green",
                          :big => "Services/Re-Sling/Finish_Selection/PC-251_Forest_Green" },
      "Burgundy" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-236_Burgundy",
                      :big => "Services/Re-Sling/Finish_Selection/PC-236_Burgundy" },
      "French Blue" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-215_French_Blue",
                         :big => "Services/Re-Sling/Finish_Selection/PC-215_French_Blue" },
      "Grey" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-219_Grey",
                  :big => "Services/Re-Sling/Finish_Selection/PC-219_Grey" },
      "Navy Blue" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-217_Navy_Blue",
                       :big => "Services/Re-Sling/Finish_Selection/PC-217_Navy_Blue" },
      "Dark Green" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-212_Dark_Green",
                        :big => "Services/Re-Sling/Finish_Selection/PC-212_Dark_Green" },
      "Camel" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-206_Camel",
                   :big => "Services/Re-Sling/Finish_Selection/PC-206_Camel" },
      "Coffee" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-238_Coffee",
                    :big => "Services/Re-Sling/Finish_Selection/PC-238_Coffee" },
      "Leisure Brown"=> { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-231_Leisure_Brown",
                          :big => "Services/Re-Sling/Finish_Selection/PC-231_Leisure_Brown" },
      "Adobe" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-232_Adobe",
                   :big => "Services/Re-Sling/Finish_Selection/PC-232_Adobe" },
      "Dove" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-252_Dove",
                  :big => "Services/Re-Sling/Finish_Selection/PC-252_Dove" },
      "Citron Yellow" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-204_Citron_Yellow",
                           :big => "Services/Re-Sling/Finish_Selection/PC-204_Citron_Yellow" },
    }
  end

  def cushion_circle_fabric
    {
      "Canvas Flax" => { :small => "SwatchBook/fabric/Cushions/5492_canvas_flax",
                         :big => "Services/Cushions/Fabric_Selection/5492_canvas_flax" },
      "Canvas Maize" => { :small => "SwatchBook/fabric/Cushions/5412_canvas_maize",
                          :big => "Services/Cushions/Fabric_Selection/5412_canvas_maize" },
      "Canvas Heather Beige" => { :small => "SwatchBook/fabric/Cushions/5476_Canvas_Heather_Beige",
                                  :big => "Services/Cushions/Fabric_Selection/5476_Canvas_Heather_Beige" },
      "Canvas Camel" => { :small => "SwatchBook/fabric/Cushions/5468_Canvas_Camel",
                          :big => "Services/Cushions/Fabric_Selection/5468_Canvas_Camel" },
      "Canvas Wheat" => { :small => "SwatchBook/fabric/Cushions/5414_Canvas_Wheat",
                          :big => "Services/Cushions/Fabric_Selection/5414_Canvas_Wheat" },
      "Canvas Buttercup" => { :small => "SwatchBook/fabric/Cushions/5438_Canvas_Buttercup",
                              :big => "Services/Cushions/Fabric_Selection/5438_Canvas_Buttercup" },
      "Canvas Sunflower" => { :small => "SwatchBook/fabric/Cushions/5457_Canvas_Sunflower",
                              :big => "Services/Cushions/Fabric_Selection/5457_Canvas_Sunflower" },
      "Canvas Tangerine" => { :small => "SwatchBook/fabric/Cushions/5406_Canvas_Tangerine",
                              :big => "Services/Cushions/Fabric_Selection/5406_Canvas_Tangerine" },
      "Canvas Tuscan" => { :small => "SwatchBook/fabric/Cushions/5417_Canvas_Tuscan",
                           :big => "Services/Cushions/Fabric_Selection/5417_Canvas_Tuscan" },
      "Canvas Henna" => { :small => "SwatchBook/fabric/Cushions/5407_Canvas_Henna",
                          :big => "Services/Cushions/Fabric_Selection/5407_Canvas_Henna" },
      "Sailcloth Shadow" => { :small => "SwatchBook/fabric/Cushions/43125_Sailcloth_Shadow",
                              :big => "Services/Cushions/Fabric_Selection/43125_Sailcloth_Shadow" },
      "Sailcloth Sailor" => { :small => "SwatchBook/fabric/Cushions/43124_Sailcloth_Sailor",
                              :big => "Services/Cushions/Fabric_Selection/43124_Sailcloth_Sailor" },
      "Frequency Ash" => { :small => "SwatchBook/fabric/Cushions/56092_Frequency_Ash",
                           :big => "Services/Cushions/Fabric_Selection/56092_Frequency_Ash" },
      "Sailcloth Sahara" => { :small => "SwatchBook/fabric/Cushions/57198_Sailcloth_Sahara",
                              :big => "Services/Cushions/Fabric_Selection/57198_Sailcloth_Sahara" },
      "Frequency Parchment" => { :small => "SwatchBook/fabric/Cushions/56093_Frequency_Parchment",
                                 :big => "Services/Cushions/Fabric_Selection/56093_Frequency_Parchment" },
      "Sailcloth Sisal" => { :small => "SwatchBook/fabric/Cushions/32001_Sailcloth_Sisal",
                             :big => "Services/Cushions/Fabric_Selection/32001_Sailcloth_Sisal" },
      "Frequency Sand" => { :small => "SwatchBook/fabric/Cushions/56094_Frequency_Sand",
                            :big => "Services/Cushions/Fabric_Selection/56094_Frequency_Sand" },
      "Echo Citron" => { :small => "SwatchBook/fabric/Cushions/8079_Echo_Citron",
                         :big => "Services/Cushions/Fabric_Selection/8079_Echo_Citron" },
      "Echo Limelite" => { :small => "SwatchBook/fabric/Cushions/8078_Echo_Limelite",
                           :big => "Services/Cushions/Fabric_Selection/8078_Echo_Limelite" },
      "Echo Midnight" => { :small => "SwatchBook/fabric/Cushions/8076_Echo_Midnight",
                           :big => "Services/Cushions/Fabric_Selection/8076_Echo_Midnight" },
      "Echo Sangria" => { :small => "SwatchBook/fabric/Cushions/8080_Echo_Sangria",
                          :big => "Services/Cushions/Fabric_Selection/8080_Echo_Sangria" },
      "Echo Teak" => { :small => "SwatchBook/fabric/Cushions/8077_Echo_Teak",
                       :big => "Services/Cushions/Fabric_Selection/8077_Echo_Teak" },
      "Dupione Deep Sea" => { :small => "SwatchBook/fabric/Cushions/8019_Dupione_Deep_Sea",
                              :big => "Services/Cushions/Fabric_Selection/8019_Dupione_Deep_Sea" },
      "Dupione Galaxy" => { :small => "SwatchBook/fabric/Cushions/8016_Dupione_Galaxy",
                            :big => "Services/Cushions/Fabric_Selection/8016_Dupione_Galaxy" },
      "Dupione Caleste" => { :small => "SwatchBook/fabric/Cushions/8067_Dupione_Celeste",
                             :big => "Services/Cushions/Fabric_Selection/8067_Dupione_Celeste" },
      "Dupione Palm" => { :small => "SwatchBook/fabric/Cushions/8052_Dupione_Palm",
                          :big => "Services/Cushions/Fabric_Selection/8052_Dupione_Palm" },
      "Dupione Laurel" => { :small => "SwatchBook/fabric/Cushions/8015_Dupione_Laurel",
                            :big => "Services/Cushions/Fabric_Selection/8015_Dupione_Laurel" },
      "Dupione Periodot" => { :small => "SwatchBook/fabric/Cushions/8024_Dupione_Peridot",
                              :big => "Services/Cushions/Fabric_Selection/8024_Dupione_Peridot" },
      "Dupione Nectarine" => { :small => "SwatchBook/fabric/Cushions/8064_Dupione_Nectarine",
                               :big => "Services/Cushions/Fabric_Selection/8064_Dupione_Nectarine" },
      "Dupione Papaya" => { :small => "SwatchBook/fabric/Cushions/8053_Dupione_Papaya",
                            :big => "Services/Cushions/Fabric_Selection/8053_Dupione_Papaya" },
      "Dupione Oak" => { :small => "SwatchBook/fabric/Cushions/8057_Dupione_Oak",
                         :big => "Services/Cushions/Fabric_Selection/8057_Dupione_Oak" },
      "Dupione Walnut" => { :small => "SwatchBook/fabric/Cushions/8017_Dupione_Walnut",
                            :big => "Services/Cushions/Fabric_Selection/8017_Dupione_Walnut" },
      "Dupione Stone" => { :small => "SwatchBook/fabric/Cushions/8060_Dupione_Stone",
                           :big => "Services/Cushions/Fabric_Selection/8060_Dupione_Stone" },
      "Dupione Caramel" => { :small => "SwatchBook/fabric/Cushions/8059_Dupione_Caramel",
                             :big => "Services/Cushions/Fabric_Selection/8059_Dupione_Caramel" },
      "Dupione Latte" => { :small => "SwatchBook/fabric/Cushions/8066_Dupione_Latte",
                           :big => "Services/Cushions/Fabric_Selection/8066_Dupione_Latte" },
      "Dupione Sand" => { :small => "SwatchBook/fabric/Cushions/8011_Dupione_Sand",
                          :big => "Services/Cushions/Fabric_Selection/8011_Dupione_Sand" },
      "Dupione Dove" => { :small => "SwatchBook/fabric/Cushions/8069_Dupione_Dove",
                          :big => "Services/Cushions/Fabric_Selection/8069_Dupione_Dove" },
      "Canvas Teak" => { :small => "SwatchBook/fabric/Cushions/5488_Canvas_Teak",
                         :big => "Services/Cushions/Fabric_Selection/5488_Canvas_Teak" },
      "Canvas Brick" => { :small => "SwatchBook/fabric/Cushions/5409_Canvas_Brick",
                          :big => "Services/Cushions/Fabric_Selection/5409_Canvas_Brick" },
      "Canvas Rust" => { :small => "SwatchBook/fabric/Cushions/54010_Canvas_Rust",
                         :big => "Services/Cushions/Fabric_Selection/54010_Canvas_Rust" },
      "Canvas Chestnut" => { :small => "SwatchBook/fabric/Cushions/57001_Canvas_Chestnut",
                             :big => "Services/Cushions/Fabric_Selection/57001_Canvas_Chestnut" },
      "Canvas Charcoal" => { :small => "SwatchBook/fabric/Cushions/54048_Canvas_Charcoal",
                             :big => "Services/Cushions/Fabric_Selection/54048_Canvas_Charcoal" },
      "Canvas Black" => { :small => "SwatchBook/fabric/Cushions/5408_Canvas_Black",
                          :big => "Services/Cushions/Fabric_Selection/5408_Canvas_Black" },
      "Canvas Pacific Blue" => { :small => "SwatchBook/fabric/Cushions/5401_Canvas_Pacific_Blue",
                                 :big => "Services/Cushions/Fabric_Selection/5401_Canvas_Pacific_Blue" },
      "Canvas Navy" => { :small => "SwatchBook/fabric/Cushions/5439_Canvas_Navy",
                         :big => "Services/Cushions/Fabric_Selection/5439_Canvas_Navy" },
      "Canvas Spa" => { :small => "SwatchBook/fabric/Cushions/5413_Canvas_Spa",
                        :big => "Services/Cushions/Fabric_Selection/5413_Canvas_Spa" },
      "Canvas Sky Blue" => { :small => "SwatchBook/fabric/Cushions/5424_Canvas_Sky_Blue",
                             :big => "Services/Cushions/Fabric_Selection/5424_Canvas_Sky_Blue" },
      "Canvas Forest Green" => { :small => "SwatchBook/fabric/Cushions/5446_Canvas_Forest_Green",
                                 :big => "Services/Cushions/Fabric_Selection/5446_Canvas_Forest_Green" },
      "Canvas Turf" => { :small => "SwatchBook/fabric/Cushions/5447_Canvas_Turf",
                         :big => "Services/Cushions/Fabric_Selection/5447_Canvas_Turf" },
      "Canvas Stone Green" => { :small => "SwatchBook/fabric/Cushions/5473_Canvas_Stone_Green",
                                :big => "Services/Cushions/Fabric_Selection/5473_Canvas_Stone_Green" },
      "Canvas Macaw" => { :small => "SwatchBook/fabric/Cushions/5429_Canvas_Macaw",
                          :big => "Services/Cushions/Fabric_Selection/5429_Canvas_Macaw" },
      "Jive Steam" => { :small => "SwatchBook/fabric/Cushions/63123_Jive_Stream",
                        :big => "Services/Cushions/Fabric_Selection/63123_Jive_Stream" },
      "Jive Sparrow" => { :small => "SwatchBook/fabric/Cushions/63122_Jive_Sparrow",
                          :big => "Services/Cushions/Fabric_Selection/63122_Jive_Sparrow" },
      "Jive Oak" => { :small => "SwatchBook/fabric/Cushions/63121_Jive_Oak",
                      :big => "Services/Cushions/Fabric_Selection/63121_Jive_Oak" },
      "Linen Natural" => { :small => "SwatchBook/fabric/Cushions/8304_Linen_Natural",
                           :big => "Services/Cushions/Fabric_Selection/8304_Linen_Natural" },
      "Linen Canvas" => { :small => "SwatchBook/fabric/Cushions/8353_Linen_Canvas",
                          :big => "Services/Cushions/Fabric_Selection/8353_Linen_Canvas" },
      "Linen Antique Beige" => { :small => "SwatchBook/fabric/Cushions/8322_Linen_Antique_Beige",
                                 :big => "Services/Cushions/Fabric_Selection/8322_Linen_Antique_Beige" },
      "Linen Champagne" => { :small => "SwatchBook/fabric/Cushions/8300_Linen_Champagne",
                             :big => "Services/Cushions/Fabric_Selection/8300_Linen_Champagne" },
      "Linen Taupe" => { :small => "SwatchBook/fabric/Cushions/8374_Linen_Taupe",
                         :big => "Services/Cushions/Fabric_Selection/8374_Linen_Taupe" },
      "Linen Stone" => { :small => "SwatchBook/fabric/Cushions/8319_Linen_Stone",
                         :big => "Services/Cushions/Fabric_Selection/8319_Linen_Stone" },
      "Linen Straw" => { :small => "SwatchBook/fabric/Cushions/8314_Linen_Straw",
                         :big => "Services/Cushions/Fabric_Selection/8314_Linen_Straw" },
      "Linen Sesame" => { :small => "SwatchBook/fabric/Cushions/8318_Linen_Sesame",
                          :big => "Services/Cushions/Fabric_Selection/8318_Linen_Sesame" },
      "Linen Pampas" => { :small => "SwatchBook/fabric/Cushions/8317_Linen_Pampas",
                          :big => "Services/Cushions/Fabric_Selection/8317_Linen_Pampas" },
      "Mainstreet Wren" => { :small => "SwatchBook/fabric/Cushions/51187_Mainstreet_Wren",
                             :big => "Services/Cushions/Fabric_Selection/51187_Mainstreet_Wren" },
      "Kamal Chestnut" => { :small => "SwatchBook/fabric/Cushions/92173_Kamal_Chestnut",
                            :big => "Services/Cushions/Fabric_Selection/92173_Kamal_Chestnut" },
      "Marcello Seaglass" => { :small => "SwatchBook/fabric/Cushions/45237_Marcello_Seaglass",
                               :big => "Services/Cushions/Fabric_Selection/45237_Marcello_Seaglass" },
      "Marcello Sunset" => { :small => "SwatchBook/fabric/Cushions/40236_Marcello_Sunset",
                             :big => "Services/Cushions/Fabric_Selection/40236_Marcello_Sunset" },
      "Forest Hills" => { :small => "SwatchBook/fabric/Cushions/1131_Forest Hills",
                          :big => "Services/Cushions/Fabric_Selection/1131_Forest Hills" },
      "Bogota" => { :small => "SwatchBook/fabric/Cushions/1174_Bogota",
                    :big => "Services/Cushions/Fabric_Selection/1174_Bogota" },
      "Caracas" => { :small => "SwatchBook/fabric/Cushions/1176_Caracas",
                     :big => "Services/Cushions/Fabric_Selection/1176_Caracas" },
      "Jockey Red" => { :small => "SwatchBook/fabric/Cushions/5403_Jockey_Red",
                        :big => "Services/Cushions/Fabric_Selection/5403_Jockey_Red" },
      "Deerfield" => { :small => "SwatchBook/fabric/Cushions/5900_Deerfield",
                       :big => "Services/Cushions/Fabric_Selection/5900_Deerfield" },
      "Natural Raffia" => { :small => "SwatchBook/fabric/Cushions/5903_Natural Raffia",
                            :big => "Services/Cushions/Fabric_Selection/5903_Natural Raffia" },
      "Rib Taupe" => { :small => "SwatchBook/fabric/Cushions/7761_Rib_Taupe",
                       :big => "Services/Cushions/Fabric_Selection/7761_Rib_Taupe" },
      "Rincon" => { :small => "SwatchBook/fabric/Cushions/10321_Rincon",
                    :big => "Services/Cushions/Fabric_Selection/10321_Rincon" },
      "Metallica" => { :small => "SwatchBook/fabric/Cushions/11309_Metallica",
                       :big => "Services/Cushions/Fabric_Selection/11309_Metallica" },
      "Gold Coast" => { :small => "SwatchBook/fabric/Cushions/11370_Gold_Coast",
                        :big => "Services/Cushions/Fabric_Selection/11370_Gold_Coast" },
      "Tarragon" => { :small => "SwatchBook/fabric/Cushions/12174_Tarragon",
                      :big => "Services/Cushions/Fabric_Selection/12174_Tarragon" },
      "Cherrywood" => { :small => "SwatchBook/fabric/Cushions/13233_Cherrywood",
                        :big => "Services/Cushions/Fabric_Selection/13233_Cherrywood" },
      "Sparkling Water" => { :small => "SwatchBook/fabric/Cushions/13381_Sparkling_Water",
                             :big => "Services/Cushions/Fabric_Selection/13381_Sparkling_Water" },
      "Royal Blue" => { :small => "SwatchBook/fabric/Cushions/14346_Royal_Blue",
                        :big => "Services/Cushions/Fabric_Selection/14346_Royal_Blue" },
      "Luxor" => { :small => "SwatchBook/fabric/Cushions/15222_Luxor",
                   :big => "Services/Cushions/Fabric_Selection/15222_Luxor" },
      "Champagne" => { :small => "SwatchBook/fabric/Cushions/19209_Champagne",
                       :big => "Services/Cushions/Fabric_Selection/19209_Champagne" },
      "Cape Cove" => { :small => "SwatchBook/fabric/Cushions/19210_Cape_Cove",
                       :big => "Services/Cushions/Fabric_Selection/19210_Cape_Cove" },
      "Hennessey" => { :small => "SwatchBook/fabric/Cushions/20116_Hennessey",
                       :big => "Services/Cushions/Fabric_Selection/20116_Hennessey" },
      "Valencia" => { :small => "SwatchBook/fabric/Cushions/20301_Valencia",
                      :big => "Services/Cushions/Fabric_Selection/20301_Valencia" },
      "Weston" => { :small => "SwatchBook/fabric/Cushions/21303_Weston",
                    :big => "Services/Cushions/Fabric_Selection/21303_Weston" },
      "Augusta" => { :small => "SwatchBook/fabric/Cushions/22109_Augusta",
                     :big => "Services/Cushions/Fabric_Selection/22109_Augusta" },
      "Pepperwood" => { :small => "SwatchBook/fabric/Cushions/29323_Pepperwood",
                        :big => "Services/Cushions/Fabric_Selection/29323_Pepperwood" },
      "Lapis" => { :small => "SwatchBook/fabric/Cushions/39106_Lapis",
                   :big => "Services/Cushions/Fabric_Selection/39106_Lapis" },
      "Caballeros" => { :small => "SwatchBook/fabric/Cushions/40330_Caballeros",
                        :big => "Services/Cushions/Fabric_Selection/40330_Caballeros" },
      "Chimayo" => { :small => "SwatchBook/fabric/Cushions/40335_Chimayo",
                     :big => "Services/Cushions/Fabric_Selection/40335_Chimayo" },
      "Seagull" => { :small => "SwatchBook/fabric/Cushions/41118_Seagull",
                     :big => "Services/Cushions/Fabric_Selection/41118_Seagull" },
      "Ecuador" => { :small => "SwatchBook/fabric/Cushions/52127_Ecuador",
                     :big => "Services/Cushions/Fabric_Selection/52127_Ecuador" },
      "Cardamon" => { :small => "SwatchBook/fabric/Cushions/54156_Cardamon",
                      :big => "Services/Cushions/Fabric_Selection/54156_Cardamon" },
      "Watercolor Tweed" => { :small => "SwatchBook/fabric/Cushions/12327_Watercolor_Tweed",
                              :big => "Services/Cushions/Fabric_Selection/12327_Watercolor_Tweed" },
      "Havana" => { :small => "SwatchBook/fabric/Cushions/54164_Havana",
                    :big => "Services/Cushions/Fabric_Selection/54164_Havana" },
    }
  end

  def umbrella_circle_fabric
    {
      "Canvas Flax" => { :small => "SwatchBook/fabric/Cushions/5492_canvas_flax",
                         :big => "Services/Cushions/Fabric_Selection/5492_canvas_flax" },
      "Canvas Maize" => { :small => "SwatchBook/fabric/Cushions/5412_canvas_maize",
                          :big => "Services/Cushions/Fabric_Selection/5412_canvas_maize" },
      "Canvas Heather Beige" => { :small => "SwatchBook/fabric/Cushions/5476_Canvas_Heather_Beige",
                                  :big => "Services/Cushions/Fabric_Selection/5476_Canvas_Heather_Beige" },
      "Canvas Camel" => { :small => "SwatchBook/fabric/Cushions/5468_Canvas_Camel",
                          :big => "Services/Cushions/Fabric_Selection/5468_Canvas_Camel" },
      "Canvas Wheat" => { :small => "SwatchBook/fabric/Cushions/5414_Canvas_Wheat",
                          :big => "Services/Cushions/Fabric_Selection/5414_Canvas_Wheat" },
      "Canvas Buttercup" => { :small => "SwatchBook/fabric/Cushions/5438_Canvas_Buttercup",
                              :big => "Services/Cushions/Fabric_Selection/5438_Canvas_Buttercup" },
      "Canvas Sunflower" => { :small => "SwatchBook/fabric/Cushions/5457_Canvas_Sunflower",
                              :big => "Services/Cushions/Fabric_Selection/5457_Canvas_Sunflower" },
      "Canvas Tangerine" => { :small => "SwatchBook/fabric/Cushions/5406_Canvas_Tangerine",
                              :big => "Services/Cushions/Fabric_Selection/5406_Canvas_Tangerine" },
      "Canvas Tuscan" => { :small => "SwatchBook/fabric/Cushions/5417_Canvas_Tuscan",
                           :big => "Services/Cushions/Fabric_Selection/5417_Canvas_Tuscan" },
      "Canvas Henna" => { :small => "SwatchBook/fabric/Cushions/5407_Canvas_Henna",
                          :big => "Services/Cushions/Fabric_Selection/5407_Canvas_Henna" },
      "Sailcloth Shadow" => { :small => "SwatchBook/fabric/Cushions/43125_Sailcloth_Shadow",
                              :big => "Services/Cushions/Fabric_Selection/43125_Sailcloth_Shadow" },
      "Sailcloth Sailor" => { :small => "SwatchBook/fabric/Cushions/43124_Sailcloth_Sailor",
                              :big => "Services/Cushions/Fabric_Selection/43124_Sailcloth_Sailor" },
      "Frequency Ash" => { :small => "SwatchBook/fabric/Cushions/56092_Frequency_Ash",
                           :big => "Services/Cushions/Fabric_Selection/56092_Frequency_Ash" },
      "Sailcloth Sahara" => { :small => "SwatchBook/fabric/Cushions/57198_Sailcloth_Sahara",
                              :big => "Services/Cushions/Fabric_Selection/57198_Sailcloth_Sahara" },
      "Frequency Parchment" => { :small => "SwatchBook/fabric/Cushions/56093_Frequency_Parchment",
                                 :big => "Services/Cushions/Fabric_Selection/56093_Frequency_Parchment" },
      "Sailcloth Sisal" => { :small => "SwatchBook/fabric/Cushions/32001_Sailcloth_Sisal",
                             :big => "Services/Cushions/Fabric_Selection/32001_Sailcloth_Sisal" },
      "Frequency Sand" => { :small => "SwatchBook/fabric/Cushions/56094_Frequency_Sand",
                            :big => "Services/Cushions/Fabric_Selection/56094_Frequency_Sand" },
      "Echo Citron" => { :small => "SwatchBook/fabric/Cushions/8079_Echo_Citron",
                         :big => "Services/Cushions/Fabric_Selection/8079_Echo_Citron" },
      "Echo Limelite" => { :small => "SwatchBook/fabric/Cushions/8078_Echo_Limelite",
                           :big => "Services/Cushions/Fabric_Selection/8078_Echo_Limelite" },
      "Echo Midnight" => { :small => "SwatchBook/fabric/Cushions/8076_Echo_Midnight",
                           :big => "Services/Cushions/Fabric_Selection/8076_Echo_Midnight" },
      "Echo Sangria" => { :small => "SwatchBook/fabric/Cushions/8080_Echo_Sangria",
                          :big => "Services/Cushions/Fabric_Selection/8080_Echo_Sangria" },
      "Echo Teak" => { :small => "SwatchBook/fabric/Cushions/8077_Echo_Teak",
                       :big => "Services/Cushions/Fabric_Selection/8077_Echo_Teak" },
      "Dupione Deep Sea" => { :small => "SwatchBook/fabric/Cushions/8019_Dupione_Deep_Sea",
                              :big => "Services/Cushions/Fabric_Selection/8019_Dupione_Deep_Sea" },
      "Dupione Galaxy" => { :small => "SwatchBook/fabric/Cushions/8016_Dupione_Galaxy",
                            :big => "Services/Cushions/Fabric_Selection/8016_Dupione_Galaxy" },
      "Dupione Caleste" => { :small => "SwatchBook/fabric/Cushions/8067_Dupione_Celeste",
                             :big => "Services/Cushions/Fabric_Selection/8067_Dupione_Celeste" },
      "Dupione Palm" => { :small => "SwatchBook/fabric/Cushions/8052_Dupione_Palm",
                          :big => "Services/Cushions/Fabric_Selection/8052_Dupione_Palm" },
      "Dupione Laurel" => { :small => "SwatchBook/fabric/Cushions/8015_Dupione_Laurel",
                            :big => "Services/Cushions/Fabric_Selection/8015_Dupione_Laurel" },
      "Dupione Periodot" => { :small => "SwatchBook/fabric/Cushions/8024_Dupione_Peridot",
                              :big => "Services/Cushions/Fabric_Selection/8024_Dupione_Peridot" },
      "Dupione Nectarine" => { :small => "SwatchBook/fabric/Cushions/8064_Dupione_Nectarine",
                               :big => "Services/Cushions/Fabric_Selection/8064_Dupione_Nectarine" },
      "Dupione Papaya" => { :small => "SwatchBook/fabric/Cushions/8053_Dupione_Papaya",
                            :big => "Services/Cushions/Fabric_Selection/8053_Dupione_Papaya" },
      "Dupione Oak" => { :small => "SwatchBook/fabric/Cushions/8057_Dupione_Oak",
                         :big => "Services/Cushions/Fabric_Selection/8057_Dupione_Oak" },
      "Dupione Walnut" => { :small => "SwatchBook/fabric/Cushions/8017_Dupione_Walnut",
                            :big => "Services/Cushions/Fabric_Selection/8017_Dupione_Walnut" },
      "Dupione Stone" => { :small => "SwatchBook/fabric/Cushions/8060_Dupione_Stone",
                           :big => "Services/Cushions/Fabric_Selection/8060_Dupione_Stone" },
      "Dupione Caramel" => { :small => "SwatchBook/fabric/Cushions/8059_Dupione_Caramel",
                             :big => "Services/Cushions/Fabric_Selection/8059_Dupione_Caramel" },
      "Dupione Latte" => { :small => "SwatchBook/fabric/Cushions/8066_Dupione_Latte",
                           :big => "Services/Cushions/Fabric_Selection/8066_Dupione_Latte" },
      "Dupione Sand" => { :small => "SwatchBook/fabric/Cushions/8011_Dupione_Sand",
                          :big => "Services/Cushions/Fabric_Selection/8011_Dupione_Sand" },
      "Dupione Dove" => { :small => "SwatchBook/fabric/Cushions/8069_Dupione_Dove",
                          :big => "Services/Cushions/Fabric_Selection/8069_Dupione_Dove" },
      "Canvas Teak" => { :small => "SwatchBook/fabric/Cushions/5488_Canvas_Teak",
                         :big => "Services/Cushions/Fabric_Selection/5488_Canvas_Teak" },
      "Canvas Brick" => { :small => "SwatchBook/fabric/Cushions/5409_Canvas_Brick",
                          :big => "Services/Cushions/Fabric_Selection/5409_Canvas_Brick" },
      "Canvas Rust" => { :small => "SwatchBook/fabric/Cushions/54010_Canvas_Rust",
                         :big => "Services/Cushions/Fabric_Selection/54010_Canvas_Rust" },
      "Canvas Chestnut" => { :small => "SwatchBook/fabric/Cushions/57001_Canvas_Chestnut",
                             :big => "Services/Cushions/Fabric_Selection/57001_Canvas_Chestnut" },
      "Canvas Charcoal" => { :small => "SwatchBook/fabric/Cushions/54048_Canvas_Charcoal",
                             :big => "Services/Cushions/Fabric_Selection/54048_Canvas_Charcoal" },
      "Canvas Black" => { :small => "SwatchBook/fabric/Cushions/5408_Canvas_Black",
                          :big => "Services/Cushions/Fabric_Selection/5408_Canvas_Black" },
      "Canvas Pacific Blue" => { :small => "SwatchBook/fabric/Cushions/5401_Canvas_Pacific_Blue",
                                 :big => "Services/Cushions/Fabric_Selection/5401_Canvas_Pacific_Blue" },
      "Canvas Navy" => { :small => "SwatchBook/fabric/Cushions/5439_Canvas_Navy",
                         :big => "Services/Cushions/Fabric_Selection/5439_Canvas_Navy" },
      "Canvas Spa" => { :small => "SwatchBook/fabric/Cushions/5413_Canvas_Spa",
                        :big => "Services/Cushions/Fabric_Selection/5413_Canvas_Spa" },
      "Canvas Sky Blue" => { :small => "SwatchBook/fabric/Cushions/5424_Canvas_Sky_Blue",
                             :big => "Services/Cushions/Fabric_Selection/5424_Canvas_Sky_Blue" },
      "Canvas Forest Green" => { :small => "SwatchBook/fabric/Cushions/5446_Canvas_Forest_Green",
                                 :big => "Services/Cushions/Fabric_Selection/5446_Canvas_Forest_Green" },
      "Canvas Turf" => { :small => "SwatchBook/fabric/Cushions/5447_Canvas_Turf",
                         :big => "Services/Cushions/Fabric_Selection/5447_Canvas_Turf" },
      "Canvas Stone Green" => { :small => "SwatchBook/fabric/Cushions/5473_Canvas_Stone_Green",
                                :big => "Services/Cushions/Fabric_Selection/5473_Canvas_Stone_Green" },
      "Canvas Macaw" => { :small => "SwatchBook/fabric/Cushions/5429_Canvas_Macaw",
                          :big => "Services/Cushions/Fabric_Selection/5429_Canvas_Macaw" },
      "Jive Steam" => { :small => "SwatchBook/fabric/Cushions/63123_Jive_Stream",
                        :big => "Services/Cushions/Fabric_Selection/63123_Jive_Stream" },
      "Jive Sparrow" => { :small => "SwatchBook/fabric/Cushions/63122_Jive_Sparrow",
                          :big => "Services/Cushions/Fabric_Selection/63122_Jive_Sparrow" },
      "Jive Oak" => { :small => "SwatchBook/fabric/Cushions/63121_Jive_Oak",
                      :big => "Services/Cushions/Fabric_Selection/63121_Jive_Oak" },
      "Linen Natural" => { :small => "SwatchBook/fabric/Cushions/8304_Linen_Natural",
                           :big => "Services/Cushions/Fabric_Selection/8304_Linen_Natural" },
      "Linen Canvas" => { :small => "SwatchBook/fabric/Cushions/8353_Linen_Canvas",
                          :big => "Services/Cushions/Fabric_Selection/8353_Linen_Canvas" },
      "Linen Antique Beige" => { :small => "SwatchBook/fabric/Cushions/8322_Linen_Antique_Beige",
                                 :big => "Services/Cushions/Fabric_Selection/8322_Linen_Antique_Beige" },
      "Linen Champagne" => { :small => "SwatchBook/fabric/Cushions/8300_Linen_Champagne",
                             :big => "Services/Cushions/Fabric_Selection/8300_Linen_Champagne" },
      "Linen Taupe" => { :small => "SwatchBook/fabric/Cushions/8374_Linen_Taupe",
                         :big => "Services/Cushions/Fabric_Selection/8374_Linen_Taupe" },
      "Linen Stone" => { :small => "SwatchBook/fabric/Cushions/8319_Linen_Stone",
                         :big => "Services/Cushions/Fabric_Selection/8319_Linen_Stone" },
      "Linen Straw" => { :small => "SwatchBook/fabric/Cushions/8314_Linen_Straw",
                         :big => "Services/Cushions/Fabric_Selection/8314_Linen_Straw" },
      "Linen Sesame" => { :small => "SwatchBook/fabric/Cushions/8318_Linen_Sesame",
                          :big => "Services/Cushions/Fabric_Selection/8318_Linen_Sesame" },
      "Linen Pampas" => { :small => "SwatchBook/fabric/Cushions/8317_Linen_Pampas",
                          :big => "Services/Cushions/Fabric_Selection/8317_Linen_Pampas" },
      "Mainstreet Wren" => { :small => "SwatchBook/fabric/Cushions/51187_Mainstreet_Wren",
                             :big => "Services/Cushions/Fabric_Selection/51187_Mainstreet_Wren" },
      "Kamal Chestnut" => { :small => "SwatchBook/fabric/Cushions/92173_Kamal_Chestnut",
                            :big => "Services/Cushions/Fabric_Selection/92173_Kamal_Chestnut" },
      "Marcello Seaglass" => { :small => "SwatchBook/fabric/Cushions/45237_Marcello_Seaglass",
                               :big => "Services/Cushions/Fabric_Selection/45237_Marcello_Seaglass" },
      "Marcello Sunset" => { :small => "SwatchBook/fabric/Cushions/40236_Marcello_Sunset",
                             :big => "Services/Cushions/Fabric_Selection/40236_Marcello_Sunset" },
      "Forest Hills" => { :small => "SwatchBook/fabric/Cushions/1131_Forest Hills",
                          :big => "Services/Cushions/Fabric_Selection/1131_Forest Hills" },
      "Bogota" => { :small => "SwatchBook/fabric/Cushions/1174_Bogota",
                    :big => "Services/Cushions/Fabric_Selection/1174_Bogota" },
      "Caracas" => { :small => "SwatchBook/fabric/Cushions/1176_Caracas",
                     :big => "Services/Cushions/Fabric_Selection/1176_Caracas" },
      "Jockey Red" => { :small => "SwatchBook/fabric/Cushions/5403_Jockey_Red",
                        :big => "Services/Cushions/Fabric_Selection/5403_Jockey_Red" },
      "Deerfield" => { :small => "SwatchBook/fabric/Cushions/5900_Deerfield",
                       :big => "Services/Cushions/Fabric_Selection/5900_Deerfield" },
      "Natural Raffia" => { :small => "SwatchBook/fabric/Cushions/5903_Natural Raffia",
                            :big => "Services/Cushions/Fabric_Selection/5903_Natural Raffia" },
      "Rib Taupe" => { :small => "SwatchBook/fabric/Cushions/7761_Rib_Taupe",
                       :big => "Services/Cushions/Fabric_Selection/7761_Rib_Taupe" },
      "Rincon" => { :small => "SwatchBook/fabric/Cushions/10321_Rincon",
                    :big => "Services/Cushions/Fabric_Selection/10321_Rincon" },
      "Metallica" => { :small => "SwatchBook/fabric/Cushions/11309_Metallica",
                       :big => "Services/Cushions/Fabric_Selection/11309_Metallica" },
      "Gold Coast" => { :small => "SwatchBook/fabric/Cushions/11370_Gold_Coast",
                        :big => "Services/Cushions/Fabric_Selection/11370_Gold_Coast" },
      "Tarragon" => { :small => "SwatchBook/fabric/Cushions/12174_Tarragon",
                      :big => "Services/Cushions/Fabric_Selection/12174_Tarragon" },
      "Cherrywood" => { :small => "SwatchBook/fabric/Cushions/13233_Cherrywood",
                        :big => "Services/Cushions/Fabric_Selection/13233_Cherrywood" },
      "Sparkling Water" => { :small => "SwatchBook/fabric/Cushions/13381_Sparkling_Water",
                             :big => "Services/Cushions/Fabric_Selection/13381_Sparkling_Water" },
      "Royal Blue" => { :small => "SwatchBook/fabric/Cushions/14346_Royal_Blue",
                        :big => "Services/Cushions/Fabric_Selection/14346_Royal_Blue" },
      "Luxor" => { :small => "SwatchBook/fabric/Cushions/15222_Luxor",
                   :big => "Services/Cushions/Fabric_Selection/15222_Luxor" },
      "Champagne" => { :small => "SwatchBook/fabric/Cushions/19209_Champagne",
                       :big => "Services/Cushions/Fabric_Selection/19209_Champagne" },
      "Cape Cove" => { :small => "SwatchBook/fabric/Cushions/19210_Cape_Cove",
                       :big => "Services/Cushions/Fabric_Selection/19210_Cape_Cove" },
      "Hennessey" => { :small => "SwatchBook/fabric/Cushions/20116_Hennessey",
                       :big => "Services/Cushions/Fabric_Selection/20116_Hennessey" },
      "Valencia" => { :small => "SwatchBook/fabric/Cushions/20301_Valencia",
                      :big => "Services/Cushions/Fabric_Selection/20301_Valencia" },
      "Weston" => { :small => "SwatchBook/fabric/Cushions/21303_Weston",
                    :big => "Services/Cushions/Fabric_Selection/21303_Weston" },
      "Augusta" => { :small => "SwatchBook/fabric/Cushions/22109_Augusta",
                     :big => "Services/Cushions/Fabric_Selection/22109_Augusta" },
      "Pepperwood" => { :small => "SwatchBook/fabric/Cushions/29323_Pepperwood",
                        :big => "Services/Cushions/Fabric_Selection/29323_Pepperwood" },
      "Lapis" => { :small => "SwatchBook/fabric/Cushions/39106_Lapis",
                   :big => "Services/Cushions/Fabric_Selection/39106_Lapis" },
      "Caballeros" => { :small => "SwatchBook/fabric/Cushions/40330_Caballeros",
                        :big => "Services/Cushions/Fabric_Selection/40330_Caballeros" },
      "Chimayo" => { :small => "SwatchBook/fabric/Cushions/40335_Chimayo",
                     :big => "Services/Cushions/Fabric_Selection/40335_Chimayo" },
      "Seagull" => { :small => "SwatchBook/fabric/Cushions/41118_Seagull",
                     :big => "Services/Cushions/Fabric_Selection/41118_Seagull" },
      "Ecuador" => { :small => "SwatchBook/fabric/Cushions/52127_Ecuador",
                     :big => "Services/Cushions/Fabric_Selection/52127_Ecuador" },
      "Cardamon" => { :small => "SwatchBook/fabric/Cushions/54156_Cardamon",
                      :big => "Services/Cushions/Fabric_Selection/54156_Cardamon" },
      "Watercolor Tweed" => { :small => "SwatchBook/fabric/Cushions/12327_Watercolor_Tweed",
                              :big => "Services/Cushions/Fabric_Selection/12327_Watercolor_Tweed" },
      "Havana" => { :small => "SwatchBook/fabric/Cushions/54164_Havana",
                    :big => "Services/Cushions/Fabric_Selection/54164_Havana" },
    }
  end

  def table_finish_pic
    {
      "Snow" => { :small => "Services/Re-Sling/Circle_Finish_Selection/SNO_Snow",
                  :big => "Services/Re-Sling/Finish_Selection/SNO_Snow" },
      "Parchment" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PMT_Parchment",
                       :big => "Services/Re-Sling/Finish_Selection/PMT_Parchment" },
      "Shell" => { :small => "Services/Re-Sling/Circle_Finish_Selection/SHL_Shell",
                   :big => "Services/Re-Sling/Finish_Selection/SHL_Shell" },
      "Sonora"=> { :small => "Services/Re-Sling/Circle_Finish_Selection/SNR_Sonora",
                   :big => "Services/Re-Sling/Finish_Selection/SNR_Sonora" },
      "Moab" => { :small => "Services/Re-Sling/Circle_Finish_Selection/MOA_Moab",
                  :big => "Services/Re-Sling/Finish_Selection/MOA_Moab" },
      "Almond Silk" => { :small => "Services/Re-Sling/Circle_Finish_Selection/ASK_Almond_Silk",
                         :big => "Services/Re-Sling/Finish_Selection/ASK_Almond_Silk" },
      "Greco" => { :small => "Services/Re-Sling/Circle_Finish_Selection/GRE_Greco",
                   :big => "Services/Re-Sling/Finish_Selection/GRE_Greco" },
      "Bronze Mica" => { :small => "Services/Re-Sling/Circle_Finish_Selection/BZM_Bronze_Mica",
                         :big => "Services/Re-Sling/Finish_Selection/BZM_Bronze_Mica" },
      "Aged Bronze" => { :small => "Services/Re-Sling/Circle_Finish_Selection/ABR_Aged_Bronze",
                         :big => "Services/Re-Sling/Finish_Selection/ABR_Aged_Bronze" },
      "Rich Earth" => { :small => "Services/Re-Sling/Circle_Finish_Selection/REA_Rich_Earth",
                        :big => "Services/Re-Sling/Finish_Selection/REA_Rich_Earth" },
      "Graphite" => { :small => "Services/Re-Sling/Circle_Finish_Selection/GPH_Graphite",
                      :big => "Services/Re-Sling/Finish_Selection/GPH_Graphite" },
      "Mocha" => { :small => "Services/Re-Sling/Circle_Finish_Selection/MOC_Mocha",
                   :big => "Services/Re-Sling/Finish_Selection/MOC_Mocha" },
      "Titanium" => { :small => "Services/Re-Sling/Circle_Finish_Selection/TIN_Titanium",
                      :big => "Services/Re-Sling/Finish_Selection/TIN_Titanium" },
      "Aluminum Metal" => { :small => "Services/Re-Sling/Circle_Finish_Selection/ALM_Aluminum_Metal",
                            :big => "Services/Re-Sling/Finish_Selection/ALM_Aluminum_Metal" },
      "Woodland Green" => { :small => "Services/Re-Sling/Circle_Finish_Selection/WLD_Woodland Green",
                            :big => "Services/Re-Sling/Finish_Selection/WLD_Woodland Green" },
      "Cobalt" => { :small => "Services/Re-Sling/Circle_Finish_Selection/CBL_Cobalt",
                    :big => "Services/Re-Sling/Finish_Selection/CBL_Cobalt" },
      "Merlot" => { :small => "Services/Re-Sling/Circle_Finish_Selection/MER_Merlot",
                    :big => "Services/Re-Sling/Finish_Selection/MER_Merlot" },
      "Obsidian" => { :small => "Services/Re-Sling/Circle_Finish_Selection/OBS_Obsidian",
                      :big => "Services/Re-Sling/Finish_Selection/OBS_Obsidian" },
      "Forest Green" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-251_Forest_Green",
                          :big => "Services/Re-Sling/Finish_Selection/PC-251_Forest_Green" },
      "Burgundy" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-236_Burgundy",
                      :big => "Services/Re-Sling/Finish_Selection/PC-236_Burgundy" },
      "French Blue" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-215_French_Blue",
                         :big => "Services/Re-Sling/Finish_Selection/PC-215_French_Blue" },
      "Grey" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-219_Grey",
                  :big => "Services/Re-Sling/Finish_Selection/PC-219_Grey" },
      "Navy Blue" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-217_Navy_Blue",
                       :big => "Services/Re-Sling/Finish_Selection/PC-217_Navy_Blue" },
      "Dark Green" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-212_Dark_Green",
                        :big => "Services/Re-Sling/Finish_Selection/PC-212_Dark_Green" },
      "Camel" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-206_Camel",
                   :big => "Services/Re-Sling/Finish_Selection/PC-206_Camel" },
      "Coffee" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-238_Coffee",
                    :big => "Services/Re-Sling/Finish_Selection/PC-238_Coffee" },
      "Leisure Brown"=> { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-231_Leisure_Brown",
                          :big => "Services/Re-Sling/Finish_Selection/PC-231_Leisure_Brown" },
      "Adobe" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-232_Adobe",
                   :big => "Services/Re-Sling/Finish_Selection/PC-232_Adobe" },
      "Dove" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-252_Dove",
                  :big => "Services/Re-Sling/Finish_Selection/PC-252_Dove" },
      "Citron Yellow" => { :small => "Services/Re-Sling/Circle_Finish_Selection/PC-204_Citron_Yellow",
                           :big => "Services/Re-Sling/Finish_Selection/PC-204_Citron_Yellow" }
    }
  end

  def resling_select_pic
    {
      "Services/Re-Sling/Photo_Selection/services_resling_S_1" => "Services/Re-Sling/Photo_Selection/services_resling_M_1",
      "Services/Re-Sling/Photo_Selection/services_resling_S_2" => "Services/Re-Sling/Photo_Selection/services_resling_M_2",
      "Services/Re-Sling/Photo_Selection/services_resling_S_3" => "Services/Re-Sling/Photo_Selection/services_resling_M_3",
      "Services/Re-Sling/Photo_Selection/services_resling_S_4" => "Services/Re-Sling/Photo_Selection/services_resling_M_4",
      "Services/Re-Sling/Photo_Selection/services_resling_S_5" => "Services/Re-Sling/Photo_Selection/services_resling_M_5",
      "Services/Re-Sling/Photo_Selection/services_resling_S_6" => "Services/Re-Sling/Photo_Selection/services_resling_M_6",
    }
  end

  def restrap_select_pic
    {
      "Services/Re-Strap/Photo_Selection/services_Strap_S_1" => "Services/Re-Strap/Photo_Selection/services_Strap_M_1",
      "Services/Re-Strap/Photo_Selection/services_Strap_S_2" => "Services/Re-Strap/Photo_Selection/services_Strap_M_2",
      "Services/Re-Strap/Photo_Selection/services_Strap_S_3" => "Services/Re-Strap/Photo_Selection/services_Strap_M_3",
      "Services/Re-Strap/Photo_Selection/services_Strap_S_4" => "Services/Re-Strap/Photo_Selection/services_Strap_M_4",
    }
  end

  def sandblast_select_pic
    {
      "Services/Sandblast_Powdercoat/Photo_Selection/Sandblast_Powdercoat_S_1" => "Services/Sandblast_Powdercoat/Photo_Selection/Sandblast_Powdercoat_M_1",
      "Services/Sandblast_Powdercoat/Photo_Selection/Sandblast_Powdercoat_S_2" => "Services/Sandblast_Powdercoat/Photo_Selection/Sandblast_Powdercoat_M_2",
    }
  end

  def cushion_select_pic
    {
      "Services/Cushions/Photo_Selection/Cushion_S_2" => "Services/Cushions/Photo_Selection/Cushion_M_2",
      "Services/Cushions/Photo_Selection/Cushion_S_3" => "Services/Cushions/Photo_Selection/Cushion_M_3",
      "Services/Cushions/Photo_Selection/Cushion_S_4" => "Services/Cushions/Photo_Selection/Cushion_M_4",
      "Services/Cushions/Photo_Selection/Cushion_S_5" => "Services/Cushions/Photo_Selection/Cushion_M_5",
    }
  end

  def table_select_pic
    {
      "Services/Tables/Photo_Selection/Table_S_1" => "Services/Tables/Photo_Selection/Table_M_1",
      "Services/Tables/Photo_Selection/Table_S_2" => "Services/Tables/Photo_Selection/Table_M_2",
      "Services/Tables/Photo_Selection/Table_S_3" => "Services/Tables/Photo_Selection/Table_M_3",
      "Services/Tables/Photo_Selection/Table_S_4" => "Services/Tables/Photo_Selection/Table_M_4",
      "Services/Tables/Photo_Selection/Table_S_5" => "Services/Tables/Photo_Selection/Table_M_5",
      "Services/Tables/Photo_Selection/Table_S_6" => "Services/Tables/Photo_Selection/Table_M_6",
    }
  end

  def umbrella_select_pic
    {
      "Services/Umbrella/Photo_Selection/Umbrella_S_1" => "Services/Umbrella/Photo_Selection/Umbrella_M_1",
      "Services/Umbrella/Photo_Selection/Umbrella_S_2" => "Services/Umbrella/Photo_Selection/Umbrella_M_2",
      "Services/Umbrella/Photo_Selection/Umbrella_S_3" => "Services/Umbrella/Photo_Selection/Umbrella_M_3",
      "Services/Umbrella/Photo_Selection/Umbrella_S_4" => "Services/Umbrella/Photo_Selection/Umbrella_M_4",
    }
  end

end
